Redirect error messages to stderr

diff --git a/usr/share/lxc/templates/lxc-jet9-centos b/usr/share/lxc/templates/lxc-jet9-centos
--- a/usr/share/lxc/templates/lxc-jet9-centos
+++ b/usr/share/lxc/templates/lxc-jet9-centos
@@ -2,6 +2,7 @@
 
 usage()
 {
+    echo "Template run error: wrong parameters" >&2
     cat <<EOF
 usage:
     $1 -n|--name=<container_name> -p|--path=<path> --rootfs=<rootfs_path>
@@ -50,16 +51,23 @@ fi
 
 ORIGIN_LXC="centos-6.5"
 
+die() {
+    # print error to stderr ent exit
+
+    _msg=$1
+    _ec=${2:-1}
+
+    echo "$_msg" >&2
+    exit $_ec
+}
+
 copy_lxc() {
     # copy origin lxc container to new one
 
     lxc_path=`dirname $path`
     touch $path/partial
     if [ -d $path ]; then
-        if [ x$force == "x" ]; then
-            echo "lxc directory $path already exists! Use -f to force" >&2
-            exit 1
-        fi
+        [ x$force == "x" ] && die "lxc directory $path already exists! Use -f to force"
         rm -rf $path
     fi
     cp -Rp $lxc_path/$ORIGIN_LXC $path
